version: 2 
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11-jdk-stretch 

    steps:      
      - checkout
      - run: curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
      - run: unzip /tmp/box.zip -d /tmp/
      - run: chmod a+x /tmp/box
      - run: /tmp/box install fixinator
      - run: mkdir /tmp/results
      - run: /tmp/box fixinator path=. confidence=low resultFormat=junit resultFile=/tmp/results/fixinator-results.xml
      
      - store_test_results: 
          path: /tmp/results/

      - store_artifacts: # uploads the result file
          path: /tmp/results/
 
