version: 2 
jobs:
  build:
    docker: 
      - image: circleci/openjdk:11-jdk-stretch 

    steps:      
      
      - run: curl --location -o /tmp/box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
      - run: unzip /tmp/box.zip -d /tmp/
      - run: chmod a+x /tmp/box
      - run: /tmp/box install fixinator
      - run: /tmp/box fixinator path=. confidence=low resultFormat=html resultFile=/tmp/fixinator-results.html
      
      - store_test_results: # uploads the test results
          path: /tmp/fixinator-results.html
 
